name: 'GitHub Release Slack Notification'
description:
  'Automatically notify Slack channels of new GitHub releases with breaking
  change detection and per-repository canvas management'
author: 'agglayer'

# Define your inputs here.
inputs:
  slack-bot-token:
    description:
      'Slack bot token (xoxb-...) with chat:write, canvases:write, and files:read permissions'
    required: true
  slack-channel:
    description:
      'Slack channel name (e.g. "releases") or ID (e.g. "C1234567890")'
    required: false
    default: 'C090TACJ9KN'
  custom-message:
    description: 'Optional custom message to include in notification'
    required: false
    default: ''
  maintain-releases-list:
    description: 'Whether to maintain per-repository canvases with latest release information'
    required: false
    default: 'true'

outputs:
  notification-sent:
    description: 'Whether the Slack notification was sent successfully'
  repository-canvas-updated:
    description: 'Whether the repository canvas was updated successfully'
  timestamp:
    description: 'ISO timestamp when the notification was sent'
  channel:
    description: 'The Slack channel where the notification was sent'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'bell'
  color: 'blue'
