name: 'GitHub Release Slack Notification'
description:
  'Automatically notify Slack channels of new GitHub releases with breaking
  change detection'
author: 'agglayer'

# Define your inputs here.
inputs:
  slack-bot-token:
    description:
      'Slack bot token (xoxb-...) with chat:write and canvases:write permissions'
    required: true
  slack-channel:
    description:
      'Slack channel name (e.g. "releases") or ID (e.g. "C1234567890")'
    required: true
  custom-message:
    description: 'Optional custom message to include in notification'
    required: false
    default: ''
  maintain-releases-list:
    description: 'Whether to maintain a releases list canvas in the channel'
    required: false
    default: 'true'

outputs:
  message-sent:
    description: 'Whether the Slack message was sent successfully'
  canvas-updated:
    description: 'Whether the releases canvas was updated successfully'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'bell'
  color: 'blue'
