name: 'GitHub Release Slack Notifier'
description: 'Send Slack notifications for GitHub releases with intelligent change detection'
author: '@sebastiendan'

# Define your inputs here.
inputs:
  slack-bot-token:
    description: 'Slack bot token (xoxb-...)'
    required: true
  slack-channel:
    description: 'Slack channel ID or name'
    required: false
    default: 'C090TACJ9KN'
  release-version:
    description: 'Release version/tag'
    required: true
  release-url:
    description: 'URL to the release page'
    required: false
  release-body:
    description: 'Release notes/body content'
    required: false
  custom-message:
    description: 'Custom message to include in the notification'
    required: false
  repository-name:
    description: 'Repository name (owner/repo format)'
    required: false

outputs:
  notification-sent:
    description: 'Whether the notification was sent successfully'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'bell'
  color: 'green'
