name: Notify release
description: Notify a release on Slack

# Define your inputs here.
inputs:
  release-version:
    description: The version of the release
    required: true
    default: 'X.Y.Z'
  slack-bot-token:
    description: >
      Slack Bot Token (starts with xoxb-). If not provided, will automatically
      use SLACK_APP_TOKEN_AGGLAYER_NOTIFY_RELEASE secret for Agglayer projects.
    required: false
  slack-channel:
    description: >
      Slack channel to post the notification (e.g., #releases, general, or
      C1234567890). The bot must be added to this channel.
    required: false
    default: '#feed_agglayer-notifier'
  release-url:
    description: URL to the release page
    required: false
  custom-message:
    description: Custom message to include with the release notification
    required: false

runs:
  using: node20
  main: dist/index.js
